apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-autoscaler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-autoscaler
  template:
    metadata:
      labels:
        app: cluster-autoscaler
    spec:
      serviceAccountName: cluster-autoscaler
      containers:
      - name: cluster-autoscaler
        image: registry.k8s.io/autoscaling/cluster-autoscaler:v1.29.0
        command:
          - ./cluster-autoscaler
          - --cloud-provider=aws
          - --cluster-name=${CLUSTER_NAME}
          - --balance-similar-node-groups
          - --skip-nodes-with-system-pods=false
          - --skip-nodes-with-local-storage=false
          - --stderrthreshold=info
          - --v=4
        env:
        - name: AWS_REGION
          value: ${AWS_REGION}

