apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaos-admin
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaos-admin
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaos-admin
subjects:
- kind: ServiceAccount
  name: chaos-admin
  namespace: default
roleRef:
  kind: ClusterRole
  name: chaos-admin
  apiGroup: rbac.authorization.k8s.io

